#!/bin/sh

# Since per-process /proc/net/ (-> /proc/self/net/) appeared,
# we need to be root
user=root
tty="/dev/tty9"

chmod -R a+X . # or else env will moan
chown $user: $tty # devfs made happy

cmd="nmeter '%t %c x %x p%p f %f b %b m %m if%[nif]'"

exec >/dev/null
exec 2>&1
exec </dev/null

eval exec \
setuidgid "$user" \
env - PATH="$PATH" \
<"$tty" >"$tty" 2>&1 \
$cmd
