# Makefile for busybox
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=
lib-$(CONFIG_HALT)	+= halt.o
lib-$(CONFIG_INIT)	+= init.o
lib-$(CONFIG_MESG)	+= mesg.o
lib-$(CONFIG_INIT)	+= init_shared.o
lib-$(CONFIG_HALT)	+= init_shared.o
