#!/bin/sh

exec 2>&1
exec </dev/null

pwd="$PWD"

if="${PWD##*/ifplugd_}"

echo "* Starting ifplugd on $if [$$]"
exec \
env - PATH="$PATH" \
softlimit \
setuidgid root \
ifplugd -apqns -t3 -u9 -d9 -i "$if" -r "$pwd/ifplugd_handler"

# we use -t3 to wake ifplugd up less often

#-a       Do not up interface automatically
#-p       Dont run script on daemon startup
#-q       Dont run script on daemon quit
#-n       Do not daemonize
#-s       Do not log to syslog
#-t SECS  Poll time in seconds
#-u SECS  Delay before running script after link up
#-d SECS  Delay after link down
#-i IFACE Interface
#-r PROG  Script to run
#-f/-F    Treat link detection error as link down/link up (otherwise exit on error)
#-M       Monitor creation/destruction of interface (otherwise it must exist)
#-x ARG   Extra argument for script
#-I       Dont exit on nonzero exit code from script
#-l       Run script on startup even if no cable is detected
#-m MODE  API mode (mii, priv, ethtool, wlan, auto)
