#!/bin/sh

grep -n -B1 -r $'^\t*}$' . | grep -A1 '.[ch]-[0-9]*-$'
grep -n -A1 -r $'^\t*{$' . | grep -B1 '.[ch]-[0-9]*-$'
# or (less surefire ones):
grep -n -B1 -r $'^\t*}' . | grep -A1 '.[ch]-[0-9]*-$'
grep -n -A1 -r $'^\t*{' . | grep -B1 '.[ch]-[0-9]*-$'
