#!/bin/sh

# Communal variables are elusize, then don't show in size output!
# This script will show all communals in *.o, sorted by size

find -name '*.o' \
| while read name; do
    b=`basename "$name"`
    nm "$name" | sed "s/^/$b: /"
done | grep -i ' c ' | sort -k2
