###
# scripts contains sources for various helper programs used throughout
# the kernel for the build process.
# ---------------------------------------------------------------------------

hostprogs-y += usage

always := $(hostprogs-y)

# Let clean descend into subdirs
subdir- += basic kconfig

HOSTCFLAGS_usage.o = -I$(srctree)/include
