=head1 NAME

busybox - I am BusyBox of Borg.  Unix will be assimilated.

=head1 SYNOPSIS

 busybox <function> [arguments...]  # or

 <function> [arguments...]	    # if symlinked

=head1 DESCRIPTION

BusyBox is a multi-call binary that combines many common Unix utilities into a
single executable.  Most people will create a symlink to busybox for each
function name, and BusyBox will act like whatever you invoke it as.

BusyBox has been written with size-optimization in mind.  It is very easy to
include or exclude the commands you want installed.  BusyBox tries to make
itself useful to small systems with limited resources.

=head1 COMMANDS

Currently defined functions:
busybox, cat, chmod, chown, chgrp, chroot, clear, chvt, cp, date,
dd, df, dmesg, du, fbset, find, free, deallocvt, fsck.minix, mkfs.minix,
grep, head, hostname, init, linuxrc, kill, ln, ls, lsmod, mkdir,
mknod, mkswap, more, mount, mv, ping, poweroff, ps, pwd, reboot,
rm, rmdir, sed, sleep, sort, sync, syslogd, swapon, swapoff, tail,
tar, tee, touch, true, false, uname, umount, uniq, update, zcat,
gunzip, gzip

Oh yes.  Unix will be mine.

=over 4

=item busybox

=item cat

=item chmod

=item chown

=item chgrp

=item chroot

=item clear

=item chvt

=item cp

=item date

=item dd

=item df

=item dmesg

=item du

=item fbset

=item find

=item free

=item deallocvt

=item fsck.minix

=item mkfs.minix

=item grep

=item head

=item hostname

=item init

=item linuxrc

=item kill

=item ln

=item ls

=item lsmod

=item mkdir

=item mknod

=item mkswap

=item more

=item mount

=item mv

=item ping

=item poweroff

=item ps

=item pwd

=item reboot

=item rm

=item rmdir

=item sed

=item sleep

=item sort

=item sync

=item syslogd

=item swapon

=item swapoff

=item tail

=item tar

=item tee

=item touch

=item true

=item false

=item uname

=item umount

=item uniq

=item update

=item zcat

=item gunzip

=item gzip

=back

=head1 SEE ALSO

textutils(1), shellutils(1), etc...

=head1 MAINTAINER

Erik Andersen <erik@lineo.com>

=head1 AUTHORS

The following people have contributed code to BusyBox whether
they know it or not.

Erik Andersen <erik@lineo.com>

=for html <br>

John Beppu <beppu@lineo.com>

=for html <br>

Brian Candler <B.Candler@pobox.com>

=for html <br>

Randolph Chung <tausq@debian.org>

=for html <br>

Dave Cinege <dcinege@psychosis.com>	

=for html <br>

Bruce Perens <bruce@perens.com>

=for html <br>

Linus Torvalds <torvalds@transmeta.com>

=for html <br>

Charles P. Wright <cpwright@villagenet.com>

=for html <br>

Enrique Zanardi <ezanardi@ull.es>

=for html <br>

=cut

