# Makefile for busybox
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=
lib-$(CONFIG_TCPSVD) += tcpudp.o ipsvd_perhost.o
lib-$(CONFIG_UDPSVD) += tcpudp.o ipsvd_perhost.o
